src/Entity/SearchTicket.php
<?php

namespace App\Entity;

use App\Repository\SearchTicketRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SearchTicketRepository::class)]
class SearchTicket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 5)]
    private ?string $from_where = null;

    #[ORM\Column(length: 5)]
    private ?string $to_where = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $departing_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $return_departing_date = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $adult = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $kid = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $infant = null;

    #[ORM\Column(nullable: true)]
    private ?float $price_total = null;

    #[ORM\Column(length: 64, nullable: true)]
    private ?string $ip_address = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?int $created_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?int $updated_by = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdult(): ?int
    {
        return $this->adult;
    }

    public function getFromWhere(): ?string
    {
        return $this->from_where;
    }

    public function setFromWhere(string $from_where): self
    {
        $this->from_where = $from_where;

        return $this;
    }

    public function getToWhere(): ?string
    {
        return $this->to_where;
    }

    public function setToWhere(string $to_where): self
    {
        $this->to_where = $to_where;

        return $this;
    }

    public function getDepartingDate(): ?\DateTimeInterface
    {
        return $this->departing_date;
    }

    public function setDepartingDate(\DateTimeInterface $departing_date): self
    {
        $this->departing_date = $departing_date;

        return $this;
    }

    public function getReturnDepartingDate(): ?\DateTimeInterface
    {
        return $this->return_departing_date;
    }

    public function setReturnDepartingDate(?\DateTimeInterface $return_departing_date): self
    {
        $this->return_departing_date = $return_departing_date;

        return $this;
    }

    public function setAdult(int $adult): self
    {
        $this->adult = $adult;

        return $this;
    }

    public function getKid(): ?int
    {
        return $this->kid;
    }

    public function setKid(?int $kid): self
    {
        $this->kid = $kid;

        return $this;
    }

    public function getInfant(): ?int
    {
        return $this->infant;
    }

    public function setInfant(?int $infant): self
    {
        $this->infant = $infant;

        return $this;
    }

    public function getPriceTotal(): ?float
    {
        return $this->price_total;
    }

    public function setPriceTotal(float $price_total): self
    {
        $this->price_total = $price_total;

        return $this;
    }

    public function getIpAddress(): ?string
    {
        return $this->ip_address;
    }

    public function setIpAddress(?string $ip_address): self
    {
        $this->ip_address = $ip_address;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?int
    {
        return $this->created_by;
    }

    public function setCreatedBy(?int $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUpdatedBy(): ?int
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?int $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?SearchTicket $search_ticket_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $airline = null;

    #[ORM\Column(length: 6, nullable: true)]
    private ?string $airline_code = null;

    #[ORM\Column(length: 16)]
    private ?string $flight_number = null;

    #[ORM\Column(length: 32, nullable: true)]
    private ?string $aircraft_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $baggage = null;

    #[ORM\Column(length: 96, nullable: true)]
    private ?string $flight_id = null;

    #[ORM\Column(length: 96, nullable: true)]
    private ?string $flight_time = null;

    #[ORM\Column(length: 8, nullable: true)]
    private ?string $carrier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $departure_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $arriving_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $return_departure_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $return_arriving_date = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $direction = null;

    #[ORM\Column]
    private ?float $adult_price = null;

    #[ORM\Column(nullable: true)]
    private ?float $price_kid = null;

    #[ORM\Column(nullable: true)]
    private ?float $price_inf = null;

    #[ORM\Column(nullable: true)]
    private ?float $tax = null;

    #[ORM\Column(nullable: true)]
    private ?float $total_price = null;

    #[ORM\Column(length: 3)]
    private ?string $currency = null;

    #[ORM\Column(nullable: true)]
    private ?float $supplier_response_price = null;

    #[ORM\Column(length: 32, nullable: true)]
    private ?string $pnr_no = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?int $created_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?int $updated_by = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $status = null;

    #[ORM\OneToMany(mappedBy: 'ticket_id', targetEntity: TicketCustomer::class)]
    private Collection $ticket_customer;

    public function __construct()
    {
        $this->ticket_customer = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSearchTicketId(): ?SearchTicket
    {
        return $this->search_ticket_id;
    }

    public function setSearchTicketId(?SearchTicket $search_ticket_id): self
    {
        $this->search_ticket_id = $search_ticket_id;

        return $this;
    }

    public function getAirline(): ?string
    {
        return $this->airline;
    }

    public function setAirline(?string $airline): self
    {
        $this->airline = $airline;

        return $this;
    }

    public function getAirlineCode(): ?string
    {
        return $this->airline_code;
    }

    public function setAirlineCode(string $airline_code): self
    {
        $this->airline_code = $airline_code;

        return $this;
    }

    public function getFlightNumber(): ?string
    {
        return $this->flight_number;
    }

    public function setFlightNumber(string $flight_number): self
    {
        $this->flight_number = $flight_number;

        return $this;
    }

    public function getAircraftType(): ?string
    {
        return $this->aircraft_type;
    }

    public function setAircraftType(?string $aircraft_type): self
    {
        $this->aircraft_type = $aircraft_type;

        return $this;
    }

    public function getBaggage(): ?string
    {
        return $this->baggage;
    }

    public function setBaggage(?string $baggage): self
    {
        $this->baggage = $baggage;

        return $this;
    }

    public function getFlightId(): ?string
    {
        return $this->flight_id;
    }

    public function setFlightId(?string $flight_id): self
    {
        $this->flight_id = $flight_id;

        return $this;
    }

    public function getFlightTime(): ?string
    {
        return $this->flight_time;
    }

    public function setFlightTime(?string $flight_time): self
    {
        $this->flight_time = $flight_time;

        return $this;
    }

    public function getCarrier(): ?string
    {
        return $this->carrier;
    }

    public function setCarrier(?string $carrier): self
    {
        $this->carrier = $carrier;

        return $this;
    }

    public function getDepartureDate(): ?\DateTimeInterface
    {
        return $this->departure_date;
    }

    public function setDepartureDate(\DateTimeInterface $departure_date): self
    {
        $this->departure_date = $departure_date;

        return $this;
    }

    public function getArrivingDate(): ?\DateTimeInterface
    {
        return $this->arriving_date;
    }

    public function setArrivingDate(\DateTimeInterface $arriving_date): self
    {
        $this->arriving_date = $arriving_date;

        return $this;
    }

    public function getReturnDepartureDate(): ?\DateTimeInterface
    {
        return $this->return_departure_date;
    }

    public function setReturnDepartureDate(?\DateTimeInterface $return_departure_date): self
    {
        $this->return_departure_date = $return_departure_date;

        return $this;
    }

    public function getReturnArrivingDate(): ?\DateTimeInterface
    {
        return $this->return_arriving_date;
    }

    public function setReturnArrivingDate(?\DateTimeInterface $return_arriving_date): self
    {
        $this->return_arriving_date = $return_arriving_date;

        return $this;
    }

    public function getDirection(): ?int
    {
        return $this->direction;
    }

    public function setDirection(int $direction): self
    {
        $this->direction = $direction;

        return $this;
    }

    public function getAdultPrice(): ?float
    {
        return $this->adult_price;
    }

    public function setAdultPrice(float $adult_price): self
    {
        $this->adult_price = $adult_price;

        return $this;
    }

    public function getPriceKid(): ?float
    {
        return $this->price_kid;
    }

    public function setPriceKid(?float $price_kid): self
    {
        $this->price_kid = $price_kid;

        return $this;
    }

    public function getPriceInf(): ?float
    {
        return $this->price_inf;
    }

    public function setPriceInf(?float $price_inf): self
    {
        $this->price_inf = $price_inf;

        return $this;
    }

    public function getTax(): ?float
    {
        return $this->tax;
    }

    public function setTax(?float $tax): self
    {
        $this->tax = $tax;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(?float $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getSupplierResponsePrice(): ?float
    {
        return $this->supplier_response_price;
    }

    public function setSupplierResponsePrice(?float $supplier_response_price): self
    {
        $this->supplier_response_price = $supplier_response_price;

        return $this;
    }

    public function getPnrNo(): ?string
    {
        return $this->pnr_no;
    }

    public function setPnrNo(?string $pnr_no): self
    {
        $this->pnr_no = $pnr_no;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?int
    {
        return $this->created_by;
    }

    public function setCreatedBy(?int $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUpdatedBy(): ?int
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?int $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, TicketCustomer>
     */
    public function getTicketCustomer(): Collection
    {
        return $this->ticket_customer;
    }

    public function addTicketCustomer(TicketCustomer $ticketCustomer): self
    {
        if (!$this->ticket_customer->contains($ticketCustomer)) {
            $this->ticket_customer->add($ticketCustomer);
            $ticketCustomer->setTicketId($this);
        }

        return $this;
    }

templates/default/booking_result.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="page-title-container">
        <div class="container">
            <div class="page-title pull-left">
                <h2 class="entry-title">Thank You</h2>
            </div>
            <ul class="breadcrumbs pull-right">
                <li><a href="{{ path('app_index') }}">HOME</a></li>
                <li class="active">Booking result</li>
            </ul>
        </div>
    </div>
    <section id="content" class="gray-area">
        <div class="container">
            <div class="row">
                <div id="main" class="col-sm-8 col-md-9">
                    <div class="booking-information travelo-box">
                        <h2>Booking Status</h2>
                        <hr />
                        {% if ticket.pnrNo!='' %}
                        <div class="booking-confirmation clearfix">
                            <i class="soap-icon-recommend icon circle"></i>
                            <div class="message">
                                <h4 class="main-message">Thank You. Your Booking Order is Confirmed Now.</h4>
                                <p>A confirmation email has been sent to your provided email address.</p>
                            </div>
                            <a href="#" class="print-button button btn-small">PRINT DETAILS</a>
                        </div>
                        {% else %}
                        <div class="booking-confirmation clearfix">
                            <i class="soap-icon-close icon circle"></i>
                            <div class="message">
                                <h4 class="text-danger">There is a proble, please contact administrator.</h4>
                            </div>
                        </div>
                        {% endif %}
                        <hr />
                        <h2>Traveler Information</h2>
                        <dl class="term-description">
                            <dt>Booking number:</dt><dd style="font-size: 18px; color: red; font-weight: bold; line-height: 1;">{{ ticket.pnrNo }}</dd>
                            <dt>Route:</dt><dd>({{ searchTicket.fromWhere }}) to ({{ searchTicket.toWhere }})</dd>
                            <dt>Date:</dt><dd>{{ ticket.departureDate|date('m-d-Y H:i') }}</dd>
                            {% if ticket.returnDepartureDate %}<dt>Return Date:</dt><dd>{{ ticket.returnDepartureDate|date('m-d-Y H:i') }}</dd>{% endif %}
                            <dt>First name:</dt><dd>{{ customer.name }}</dd>
                            <dt>Last name:</dt><dd>{{ customer.surname }}</dd>
                            <dt>E-mail:</dt><dd>{{ customer.email }}</dd>
                            <dt>Phone:</dt><dd>{{ customer.phone }}</dd>
                        </dl>
                    </div>
                </div>
                <div class="sidebar col-sm-4 col-md-3">
                    <div class="travelo-box contact-box">
                        <h4>Need Genius Help?</h4>
                        <p>We would be more than happy to help you. Our team advisor are 24/7 at your service to help you.</p>
                        <address class="contact-details">
                            <span class="contact-phone"><i class="soap-icon-phone"></i> 1-800-123-HELLO</span>
                            <br>
                            <a class="contact-email" href="#">help@genius.com</a>
                        </address>
                    </div>
                    <div class="travelo-box book-with-us-box">
                        <h4>Why Book with us?</h4>
                        <ul>
                            <li>
                                <i class="soap-icon-plane circle"></i>
                                <h5 class="title"><a href="#">35+ Airlines</a></h5>
                                <p>Nunc cursus libero pur congue arut nimspnty.</p>
                            </li>
                            <li>
                                <i class="soap-icon-party circle"></i>
                                <h5 class="title"><a href="#">Low Rates &amp; Savings</a></h5>
                                <p>Nunc cursus libero pur congue arut nimspnty.</p>
                            </li>
                            <li>
                                <i class="soap-icon-support circle"></i>
                                <h5 class="title"><a href="#">Excellent Support</a></h5>
                                <p>Nunc cursus libero pur congue arut nimspnty.</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

templates/default/flight_results.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        article .box { margin-bottom: 0; }
        .listing-style3 .box, .listing-style3.box {
            margin-bottom: 0;
        }
    </style>
{% endblock stylesheets %}

{% block content %}
    <div class="page-title-container">
        <div class="container">
            <div class="page-title pull-left">
                <h2 class="entry-title">Flight Search Results</h2>
            </div>
            <ul class="breadcrumbs pull-right">
                <li><a href="{{ path('app_index') }}">HOME</a></li>
                <li class="active">Flight Search Results</li>
            </ul>
        </div>
    </div>

    <section id="content">
        <div class="container">
            <div id="main">
                <div class="row">
                    <div class="col-sm-4 col-md-3">
                        <h4 class="search-results-title"><i class="soap-icon-search"></i><b id="result_count">...</b> results found.</h4>
                        <div class="toggle-container filters-container">
                            <div class="panel style1 arrow-right">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" href="#airlines-filter" class="collapsed">Airlines</a>
                                </h4>
                                <div id="airlines-filter" class="panel-collapse collapse">
                                    <div class="panel-content">
                                        <ul class="check-square filters-option airlines_ait">
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="panel style1 arrow-right">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" href="#modify-search-panel" class="" aria-expanded="true">Modify Search</a>
                                </h4>
                                <div id="modify-search-panel" class="panel-collapse collapse in">
                                    <div class="panel-content">
                                        <form action="{{ path('app_flight_results') }}" method="get">
                                            <div class="form-group">
                                                <label>Leaving from</label>
                                                <input type="text" name="fromWhere" class="input-text full-width" placeholder="" value="{{ search.fromWhere }}" />
                                            </div>
                                            <div class="form-group">
                                                <label>To</label>
                                                <input type="text" name="toWhere" class="input-text full-width" placeholder="" value="{{ search.toWhere }}" />
                                            </div>
                                            <div class="form-group">
                                                <label>Departure on</label>
                                                <div class="datepicker-wrap">
                                                    <input type="text" name="departDate" class="input-text full-width" placeholder="mm/dd/yy" value="{{ search.departDate }}" />
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Arriving On</label>
                                                <div class="datepicker-wrap">
                                                    <input type="text" name="returnDate" class="input-text full-width" placeholder="mm/dd/yy" value="{{ search.returnDate }}" />
                                                </div>
                                            </div>
                                            <div class="form-group" style="float: left; width: 33%;">
                                                <label>Adults</label>
                                                <input type="number" class="input-text full-width" name="whoADT" value="{{ search.whoADT }}" placeholder="" min="1" max="15" />
                                            </div>
                                            <div class="form-group" style="float: left; width: 33%;">
                                                <label>Kids</label>
                                                <input type="number" class="input-text full-width" name="whoKid" value="{{ search.whoKid }}" placeholder="" min="0" max="5" />
                                            </div>
                                            <div class="form-group" style="float: left; width: 33%;">
                                                <label>Infants</label>
                                                <input type="number" class="input-text full-width" name="whoInf" value="{{ search.whoInf }}" placeholder="" min="0" max="3" />
                                            </div>
                                            <br />
                                            <button type="submit" class="btn-medium icon-check uppercase full-width">search again</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8 col-md-9">
                        <div class="sort-by-section clearfix box">
                            <h4 class="sort-by-title block-sm">Sort results by:</h4>
                            <ul class="sort-bar clearfix block-sm">
                                <li class="sort-by-name"><a class="sort-by-container" href="#"><span>name</span></a></li>
                                <li class="sort-by-price"><a class="sort-by-container" href="#"><span>price</span></a></li>
                                <li class="sort-by-rating active"><a class="sort-by-container" href="#"><span>duration</span></a></li>
                            </ul>

                            <ul class="swap-tiles clearfix block-sm">
                                <li class="swap-list active">
                                    <a href="#"><i class="soap-icon-list"></i></a>
                                </li>
                                <li class="swap-grid">
                                    <a href="#"><i class="soap-icon-grid"></i></a>
                                </li>
                                <li class="swap-block">
                                    <a href="#"><i class="soap-icon-block"></i></a>
                                </li>
                            </ul>
                        </div>

                        <div class="flight-list listing-style3 flight" id="flight_results"></div>

                        <a class="button uppercase full-width btn-large" style="display: none;">load more listings</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/flight_results.js') }}"></script>
{% endblock javascripts %}